/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.infrastructure.api;

import com.example.infrastructure.models.Error;
import com.example.infrastructure.models.Order;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

import java.util.List;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-05-16T17:35:02.597539500+02:00[Europe/Warsaw]")
@Validated
@Api(value = "ordersForItem", description = "the ordersForItem API")
public interface OrdersForItemApi {

    default OrdersForItemApiDelegate getDelegate() {
        return new OrdersForItemApiDelegate() {};
    }

    /**
     * GET /ordersForItem/{itemId} : List all orders containing item
     *
     * @param itemId  (required)
     * @return A list of orders containing item. (status code 200)
     *         or unexpected error (status code 400)
     */
    @ApiOperation(value = "List all orders containing item", nickname = "ordersForItemItemIdGet", notes = "", response = Order.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A list of orders containing item.", response = Order.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "unexpected error", response = Error.class) })
    @GetMapping(
        value = "/ordersForItem/{itemId}",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Order>> ordersForItemItemIdGet(@ApiParam(value = "",required=true) @PathVariable("itemId") Integer itemId) {
        return getDelegate().ordersForItemItemIdGet(itemId);
    }

}
