/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.example.infrastructure.api;

import com.example.infrastructure.models.Error;
import com.example.infrastructure.models.Tracking;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-05-16T17:35:02.597539500+02:00[Europe/Warsaw]")
@Validated
@Api(value = "trackingForDelivery", description = "the trackingForDelivery API")
public interface TrackingForDeliveryApi {

    default TrackingForDeliveryApiDelegate getDelegate() {
        return new TrackingForDeliveryApiDelegate() {};
    }

    /**
     * GET /trackingForDelivery/{id} : Get tracking by delviery id
     *
     * @param id  (required)
     * @return Get tracking by delivery id (status code 200)
     *         or unexpected error (status code 400)
     */
    @ApiOperation(value = "Get tracking by delviery id", nickname = "trackingForDeliveryIdGet", notes = "", response = Tracking.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Get tracking by delivery id", response = Tracking.class),
        @ApiResponse(code = 400, message = "unexpected error", response = Error.class) })
    @GetMapping(
        value = "/trackingForDelivery/{id}",
        produces = { "application/json" }
    )
    default ResponseEntity<Tracking> trackingForDeliveryIdGet(@ApiParam(value = "",required=true) @PathVariable("id") Integer id) {
        return getDelegate().trackingForDeliveryIdGet(id);
    }

}
